# -*- coding: utf-8 -*-
"""DSc_Project_TourPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbasT0SXL2lAJpdD5TuoLBqjM8fulwgd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.offline as pyo
import plotly.io as pio
from plotly.offline import iplot
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder
!pip install catboost
!pip install xgboost
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from scipy.stats import chi2_contingency, shapiro
import warnings
warnings.filterwarnings('ignore')

# Set display options for better visualization
pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

# Load the dataset
print("Loading dataset...")
df = pd.read_csv('/content/tourism_resource_dataset.csv')
print("Dataset loaded successfully!")

# Clean column names
df.columns = df.columns.str.replace(" ", "_")

print("Dataset Preview:")
display(df.head())

# -------------------------------------------------
# Data Preprocessing and Inspection
# -------------------------------------------------

# Convert timestamp to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Check for missing values
missing_data = df.isnull().sum()
print("Missing data in each column:\n", missing_data)

# Drop rows with missing values if any
df_cleaned = df.dropna()
missing_data_after_cleaning = df_cleaned.isnull().sum()
print("\nMissing data after cleaning:\n", missing_data_after_cleaning)

# Check for duplicate rows
print(f"Number of duplicate rows: {df.duplicated().sum()}")

# Function to get column types
def grab_col_names(dataframe, cat_th=10, car_th=20):
    # cat_cols, cat_but_car
    cat_cols = [col for col in dataframe.columns if dataframe[col].dtypes == "O"]
    num_but_cat = [col for col in dataframe.columns if dataframe[col].nunique() < cat_th and dataframe[col].dtypes != "O"]
    cat_but_car = [col for col in dataframe.columns if dataframe[col].nunique() > car_th and dataframe[col].dtypes == "O"]
    cat_cols = cat_cols + num_but_cat
    cat_cols = [col for col in cat_cols if col not in cat_but_car]

    # num_cols
    num_cols = [col for col in dataframe.columns if dataframe[col].dtypes != "O"]
    num_cols = [col for col in num_cols if col not in num_but_cat]

    print(f"Observations: {dataframe.shape[0]}")
    print(f"Variables: {dataframe.shape[1]}")
    print(f'cat_cols: {len(cat_cols)}')
    print(f'num_cols: {len(num_cols)}')
    print(f'cat_but_car: {len(cat_but_car)}')
    print(f'num_but_cat: {len(num_but_cat)}')

    return cat_cols, num_cols, cat_but_car

cat_cols, num_cols, cat_but_car = grab_col_names(df)
print("Categorical columns:", cat_cols)
print("Numerical columns:", num_cols)

# -------------------------------------------------
# Data Summary Statistics
# -------------------------------------------------

# Summary statistics for environmental factors
env_factors = df_cleaned[['temperature', 'air_quality_index', 'noise_level']]
summary_stats = env_factors.describe()
print("Summary statistics for environmental factors:\n", summary_stats)

# Test for numerical homogeneity: Identify outliers using the IQR method
print("\nOutlier Analysis:")
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns
for col in numerical_columns:
    Q1 = df[col].quantile(0.25)  # First quartile
    Q3 = df[col].quantile(0.75)  # Third quartile
    IQR = Q3 - Q1  # Interquartile range

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"Column: {col}\nOutliers Detected: {len(outliers)}\n")

# Normality Test for Numerical Columns
print("\nNormality Tests:")
for col in num_cols:
    stat, p = shapiro(df[col])
    print(f"Shapiro-Wilk Test for {col}:")
    if p > 0.05:
        print(f"P-Value: {p} -> Data appears to be normally distributed.\n")
    else:
        print(f"P-Value: {p} -> Data does not appear to be normally distributed.\n")

# -------------------------------------------------
# Exploratory Data Analysis (EDA)
# -------------------------------------------------

# Function for categorical data visualization
def cat_summary(dataframe, col_name, plot=False):
    print(pd.DataFrame({col_name: dataframe[col_name].value_counts(),
                        "Ratio": 100 * dataframe[col_name].value_counts() / len(dataframe)}))

    if plot:
        fig, axs = plt.subplots(1, 2, figsize=(12, 6))
        plt.subplot(1, 2, 1)
        sns.countplot(x=dataframe[col_name], data=dataframe, palette="Set1")
        plt.title("Frequency of " + col_name)
        plt.xticks(rotation=90)

        plt.subplot(1, 2, 2)
        values = dataframe[col_name].value_counts()
        plt.pie(x=values, labels=values.index, autopct=lambda p: '{:.2f}% ({:.0f})'.format(p, p/100 * sum(values)))
        hole = plt.Circle((0, 0), 0.40, facecolor='white')
        plt.gcf().gca().add_artist(hole)
        plt.title("Frequency of " + col_name)
        plt.legend(labels=['{} - {:.2f}%'.format(index, value/sum(values)*100) for index, value in zip(values.index, values)],
                   loc='upper center', bbox_to_anchor=(0.5, -0.2), fancybox=True, shadow=True, ncol=1)
        plt.show()

print("\nCategorical Data Analysis:")
for col in cat_cols:
    cat_summary(df, col, True)

# Distribution plots for numerical columns
def generate_distribution_plot(df, num_cols):
    # Create copy of dataframe
    data = df[num_cols].copy()
    # Create subplots
    n_cols = min(2, len(data.columns))
    n_rows = (len(data.columns) + n_cols - 1) // n_cols
    fig, axes = plt.subplots(nrows=n_rows, ncols=n_cols, figsize=(15, 3*n_rows))
    fig.subplots_adjust(hspace=0.7)

    # Set fontdict
    font = {'family': 'serif',
        'color':  'darkred',
        'weight': 'normal',
        'size': 16,
        }

    # Generate distplot
    for ax, feature in zip(axes.flatten(), data.columns):
        feature_mean = data[feature].mean()
        feature_median = data[feature].median()
        feature_mode = data[feature].mode().values[0]
        sns.histplot(data[feature], kde=True, ax=ax)
        ax.set_title(f'Analysis of {feature}', fontdict=font)
        ax.axvline(feature_mean, color='r', linestyle='--', label="Mean")
        ax.axvline(feature_median, color='g', linestyle='--', label="Median")
        ax.axvline(feature_mode, color='b', linestyle='--', label="Mode")
        ax.legend()

    # Hide any unused subplots
    for i in range(len(data.columns), n_rows * n_cols):
        fig.delaxes(axes.flatten()[i])

    plt.show()

print("\nNumerical Data Distribution Analysis:")
generate_distribution_plot(df, num_cols)

# Distribution of environmental factors
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
sns.histplot(df_cleaned['temperature'], kde=True, color='skyblue')
plt.title('Temperature Distribution')

plt.subplot(1, 3, 2)
sns.histplot(df_cleaned['air_quality_index'], kde=True, color='lightgreen')
plt.title('Air Quality Index Distribution')

plt.subplot(1, 3, 3)
sns.histplot(df_cleaned['noise_level'], kde=True, color='salmon')
plt.title('Noise Level Distribution')

plt.tight_layout()
plt.show()

# Correlation matrix visualization
correlation_matrix = df_cleaned[['visitor_count', 'temperature', 'air_quality_index', 'noise_level', 'visitor_satisfaction', 'resource_prediction']].corr()

plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title("Correlation Matrix")
plt.show()

# Environmental factors vs Visitor Count
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
sns.scatterplot(x=df_cleaned['temperature'], y=df_cleaned['visitor_count'], color='skyblue')
plt.title('Temperature vs Visitor Count')

plt.subplot(1, 3, 2)
sns.scatterplot(x=df_cleaned['air_quality_index'], y=df_cleaned['visitor_count'], color='lightgreen')
plt.title('Air Quality Index vs Visitor Count')

plt.subplot(1, 3, 3)
sns.scatterplot(x=df_cleaned['noise_level'], y=df_cleaned['visitor_count'], color='salmon')
plt.title('Noise Level vs Visitor Count')

plt.tight_layout()
plt.show()

# Visitor Count by Season
plt.figure(figsize=(10, 6))
sns.boxplot(x='season', y='visitor_count', data=df)
plt.title('Visitor Count by Season')
plt.xlabel('Season')
plt.ylabel('Visitor Count')
plt.show()

# Bin environmental factors for better analysis
temperature_bins = [0, 15, 20, 25, 30, 35, np.inf]
temperature_labels = ['<15', '15-20', '20-25', '25-30', '30-35', '>35']
df_cleaned['temperature_range'] = pd.cut(df_cleaned['temperature'], bins=temperature_bins, labels=temperature_labels)

air_quality_bins = [0, 50, 100, 150, np.inf]
air_quality_labels = ['0-50', '50-100', '100-150', '>150']
df_cleaned['air_quality_range'] = pd.cut(df_cleaned['air_quality_index'], bins=air_quality_bins, labels=air_quality_labels)

noise_level_bins = [0, 40, 60, 80, 100, np.inf]
noise_level_labels = ['0-40', '40-60', '60-80', '80-100', '>100']
df_cleaned['noise_level_range'] = pd.cut(df_cleaned['noise_level'], bins=noise_level_bins, labels=noise_level_labels)

# Average visitor count by environmental factor ranges
temperature_avg = df_cleaned.groupby('temperature_range')['visitor_count'].mean()
air_quality_avg = df_cleaned.groupby('air_quality_range')['visitor_count'].mean()
noise_level_avg = df_cleaned.groupby('noise_level_range')['visitor_count'].mean()

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
temperature_avg.plot(kind='bar', color='skyblue')
plt.title('Average Visitor Count by Temperature Range')
plt.ylabel('Average Visitor Count')

plt.subplot(1, 3, 2)
air_quality_avg.plot(kind='bar', color='lightgreen')
plt.title('Average Visitor Count by Air Quality Range')
plt.ylabel('Average Visitor Count')

plt.subplot(1, 3, 3)
noise_level_avg.plot(kind='bar', color='salmon')
plt.title('Average Visitor Count by Noise Level Range')
plt.ylabel('Average Visitor Count')

plt.tight_layout()
plt.show()

# Visitor satisfaction by environmental factor ranges
temperature_satisfaction = df_cleaned.groupby('temperature_range')['visitor_satisfaction'].mean()
air_quality_satisfaction = df_cleaned.groupby('air_quality_range')['visitor_satisfaction'].mean()
noise_level_satisfaction = df_cleaned.groupby('noise_level_range')['visitor_satisfaction'].mean()

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
temperature_satisfaction.plot(kind='bar', color='skyblue')
plt.title('Visitor Satisfaction by Temperature Range')
plt.ylabel('Average Visitor Satisfaction')

plt.subplot(1, 3, 2)
air_quality_satisfaction.plot(kind='bar', color='lightgreen')
plt.title('Visitor Satisfaction by Air Quality Range')
plt.ylabel('Average Visitor Satisfaction')

plt.subplot(1, 3, 3)
noise_level_satisfaction.plot(kind='bar', color='salmon')
plt.title('Visitor Satisfaction by Noise Level Range')
plt.ylabel('Average Visitor Satisfaction')

plt.tight_layout()
plt.show()

# Advanced visualizations

# Visitor satisfaction across season and resource allocation
plt.figure(figsize=(12, 6))
sns.barplot(x='season', y='visitor_satisfaction', hue='resource_allocation', data=df, palette="Paired")
plt.title("Visitor Satisfaction Across Season and Resource Allocation")
plt.xlabel("Season")
plt.ylabel("Visitor Satisfaction")
plt.xticks(rotation=0)
plt.legend(loc='upper left', bbox_to_anchor=(1,1), title='Resource Allocation')
plt.show()

# Heatmap of season resource prediction for location_id
heatmap_df = df.pivot_table(values='resource_prediction', index='season', columns='location_id', aggfunc='mean')
plt.figure(figsize=(10, 6))
sns.heatmap(heatmap_df, cmap="YlGnBu", annot=True, fmt=".2f")
plt.title("Heatmap of Season Resource Prediction by Location ID")
plt.xlabel("Location ID")
plt.ylabel("Season")
plt.show()

# Relationship between resource prediction and visitor count by resource allocation and location_id
plt.figure(figsize=(10, 6))
sns.scatterplot(x='resource_prediction', y='visitor_count', hue='resource_allocation', style='location_id', data=df, palette="Set1")
plt.title("Relationship Between Resource Prediction and Visitor Count")
plt.xlabel("Resource Prediction")
plt.ylabel("Visitor Count")
plt.legend(title="Resource Allocation & Location ID")
plt.show()

# Pairplot for numerical relationships
sns.pairplot(df, hue='resource_allocation', vars=[
    'visitor_count', 'resource_usage_rate', 'temperature',
    'air_quality_index', 'noise_level', 'visitor_satisfaction', 'resource_prediction'
], palette="husl")
plt.suptitle("Pairplot of Key Numerical Features", y=1.02)
plt.show()

# -------------------------------------------------
# Machine Learning: Regression Models
# -------------------------------------------------

print("\n----- REGRESSION MODELING -----")
print("Predicting resource_prediction based on environmental factors")

# Create dummy variables for categorical columns
df_ml = df_cleaned.copy()
df_ml = pd.get_dummies(df_ml, columns=['location_id', 'season', 'resource_allocation'], drop_first=True)

# Convert resource prediction to numeric
df_ml['resource_prediction'] = pd.to_numeric(df_ml['resource_prediction'], errors='coerce')
df_ml = df_ml.dropna(subset=['resource_prediction'])

# Features and target for regression
X_reg = df_ml[['visitor_count', 'temperature', 'air_quality_index', 'noise_level', 'visitor_satisfaction', 'peak_hour_flag', 'sensor_noise_flag']]
y_reg = df_ml['resource_prediction']

# Train-test split
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

print(f"Training set size: {len(X_train_reg)}")
print(f"Test set size: {len(X_test_reg)}")

# Linear Regression
lr_model = LinearRegression()
lr_model.fit(X_train_reg, y_train_reg)
y_pred_lr = lr_model.predict(X_test_reg)
mse_lr = mean_squared_error(y_test_reg, y_pred_lr)
r2_lr = r2_score(y_test_reg, y_pred_lr)

print(f"Linear Regression MSE: {mse_lr:.4f}")
print(f"Linear Regression R²: {r2_lr:.4f}")

# Random Forest Regression
rf_reg_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_reg_model.fit(X_train_reg, y_train_reg)

y_pred_rf_reg = rf_reg_model.predict(X_test_reg)
mse_rf_reg = mean_squared_error(y_test_reg, y_pred_rf_reg)
r2_rf_reg = r2_score(y_test_reg, y_pred_rf_reg)

print(f"Random Forest Regression MSE: {mse_rf_reg:.4f}")
print(f"Random Forest Regression R²: {r2_rf_reg:.4f}")

# Feature importance for Random Forest Regression
feature_importance = pd.DataFrame({
    'Feature': X_reg.columns,
    'Importance': rf_reg_model.feature_importances_
}).sort_values('Importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance)
plt.title('Feature Importance for Resource Prediction')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

# -------------------------------------------------
# Machine Learning: Classification Models
# -------------------------------------------------

print("\n----- CLASSIFICATION MODELING -----")
print("Predicting resource_allocation based on all features")

# Prepare data for classification
# Drop timestamp for classification tasks
df_class = df.copy()

# Save original values for later decoding
original_resource_allocation = df_class['resource_allocation'].unique()

# Convert categorical variables using Label Encoding
label_encoders = {}
categorical_columns = df_class.select_dtypes(include=['object']).columns

for column in categorical_columns:
    label_encoders[column] = LabelEncoder()
    df_class[column] = label_encoders[column].fit_transform(df_class[column])

    encoded_values = df_class[column].unique()
    decoded_values = label_encoders[column].inverse_transform(encoded_values)

    print(f"\n{column} Encoding and Decoding:")
    for enc, dec in zip(encoded_values, decoded_values):
        print(f"{enc} -> {dec}")

# Split data for classification model
X_class = df_class.drop(['resource_allocation', 'timestamp'], axis=1)
y_class = df_class['resource_allocation']

# Train-test split
X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(X_class, y_class, test_size=0.2, random_state=42)
print(f"\nTraining Set: {X_train_class.shape}, Testing Set: {X_test_class.shape}")

# Scale the features
scaler = StandardScaler()
X_train_class_scaled = scaler.fit_transform(X_train_class)
X_test_class_scaled = scaler.transform(X_test_class)

# Define classification models
classification_models = {
    'CatBoost': CatBoostClassifier(verbose=False, random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'XGBoost': XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
}

# Train and evaluate classification models
class_results = []

for model_name, model in classification_models.items():
    try:
        # Train the model
        model.fit(X_train_class_scaled, y_train_class)

        # Make predictions
        y_pred_class = model.predict(X_test_class_scaled)

        # Evaluate the model
        accuracy = accuracy_score(y_test_class, y_pred_class)
        class_results.append((model_name, accuracy))

        print(f"\n{model_name} Results:")
        print(f"Accuracy: {accuracy:.4f}")

        # Classification report
        print("\nClassification Report:")
        print(classification_report(y_test_class, y_pred_class))

        # Confusion Matrix
        plt.figure(figsize=(8, 6))
        cm = confusion_matrix(y_test_class, y_pred_class)
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
        plt.title(f'Confusion Matrix - {model_name}')
        plt.xlabel('Predicted Label')
        plt.ylabel('True Label')
        plt.show()

    except Exception as e:
        print(f"\n{model_name} failed with error: {e}")

# Cross-validation for the best classification model
if class_results:
    best_class_model_name = max(class_results, key=lambda x: x[1])[0]
    print(f"\nBest Classification Model: {best_class_model_name}")

    # Cross-validation
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(classification_models[best_class_model_name],
                               X_train_class_scaled, y_train_class,
                               cv=kf, scoring='accuracy')

    print(f"Cross-Validation Scores: {cv_scores}")
    print(f"Mean CV Score: {cv_scores.mean():.4f}")
    print(f"Standard Deviation: {cv_scores.std():.4f}")

# -------------------------------------------------
# Feature Importance Analysis
# -------------------------------------------------

# Feature importance for the best classification model
if 'Random Forest' in classification_models:
    rf_classifier = classification_models['Random Forest']
    feature_imp = pd.DataFrame({
        'Feature': X_class.columns,
        'Importance': rf_classifier.feature_importances_
    }).sort_values(by='Importance', ascending=False)

    plt.figure(figsize=(10, 6))
    sns.barplot(x='Importance', y='Feature', data=feature_imp)
    plt.title('Feature Importance for Resource Allocation Classification')
    plt.xlabel('Importance')
    plt.ylabel('Feature')
    plt.tight_layout()
    plt.show()

# -------------------------------------------------
# Conclusion
# -------------------------------------------------

print("\n---- ANALYSIS SUMMARY ----")
print("1. Data Overview:")
print(f"   - Total observations: {df.shape[0]}")
print(f"   - Missing values: {df.isnull().sum().sum()}")

print("\n2. Key Findings:")
print(f"   - Best regression model: Random Forest with R² of {r2_rf_reg:.4f}")
if class_results:
    best_class_model = max(class_results, key=lambda x: x[1])
    print(f"   - Best classification model: {best_class_model[0]} with accuracy of {best_class_model[1]:.4f}")

print("\n3. Environmental Impact:")
print("   - Temperature range with highest visitor count:", temperature_avg.idxmax())
print("   - Air quality range with highest visitor satisfaction:", air_quality_satisfaction.idxmax())
print("   - Noise level range with highest visitor satisfaction:", noise_level_satisfaction.idxmax())

print("\n4. Recommendations:")
print("   - Optimize resource allocation based on environmental factors")
print("   - Focus on visitor satisfaction in relation to environmental conditions")
print("   - Consider seasonal patterns in resource management planning")

print("\nAnalysis Complete!")